<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quant 1 - homework 1 key</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Quant 1</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lecture.html" rel="" target="">
 <span class="menu-text">Lectures</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./homework.html" rel="" target="">
 <span class="menu-text">Homework</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./syllabus.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#note" id="toc-note" class="nav-link active" data-scroll-target="#note">NOTE</a></li>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data">Load data</a></li>
  <li><a href="#q1-calculate-descriptive-statistics-for-each-of-the-4-world-groups." id="toc-q1-calculate-descriptive-statistics-for-each-of-the-4-world-groups." class="nav-link" data-scroll-target="#q1-calculate-descriptive-statistics-for-each-of-the-4-world-groups.">Q1 Calculate descriptive statistics for each of the 4 World groups.</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">homework 1 key</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="note" class="level2">
<h2 class="anchored" data-anchor-id="note">NOTE</h2>
<p>These answers are only one way to do it. The great thing about R is that there are many roads to the right answer. You do not need to have exactly the same code to get full points. The key is here to show you merely one solution of the homework.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">55555</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="do">##Load packages</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'

The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'</code></pre>
</div>
</div>
</section>
<section id="load-data" class="level2">
<h2 class="anchored" data-anchor-id="load-data">Load data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"homework-world.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>World <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>World)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="q1-calculate-descriptive-statistics-for-each-of-the-4-world-groups." class="level2">
<h2 class="anchored" data-anchor-id="q1-calculate-descriptive-statistics-for-each-of-the-4-world-groups.">Q1 Calculate descriptive statistics for each of the 4 World groups.</h2>
<p>That is, you should get the mean GDP for countries that are coded as 1 in the World variable, mean GDP for countries coded as 2 in the World variable etc. This should include (it’s OK if more are included, but at least these): - mean - median - range - min &amp; max - standard deviation - skew &amp; kurtosis</p>
<p>For this question, you can use various coding approaches to calculate each of the descriptives separately for each group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Create a list of the variables we are interested in</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>continuous_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Happiness"</span>, <span class="st">"GDP"</span>, <span class="st">"Support"</span>, <span class="st">"Life"</span>, <span class="st">"Freedom"</span>, <span class="st">"Generosity"</span>, <span class="st">"Corruption"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="do">##Define a function to calculate all our descriptive statistics within a given World group </span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="do">##for a given variable</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">&lt;-</span> <span class="cf">function</span>(data, world_group, variable){</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="do">##Filter dataset to only the World group of interest</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(World <span class="sc">==</span> world_group)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="do">##Calculate descriptive statistics on the variable of interest</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  stat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">mean =</span> <span class="fu">mean</span>(<span class="fu">na.omit</span>(data[,<span class="fu">paste0</span>(variable)])),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>                     <span class="at">median =</span> <span class="fu">median</span>(<span class="fu">na.omit</span>(data[,<span class="fu">paste0</span>(variable)])),</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>                     <span class="at">range =</span> <span class="fu">max</span>(<span class="fu">na.omit</span>(data[,<span class="fu">paste0</span>(variable)])) </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>                           <span class="sc">-</span> <span class="fu">min</span>(<span class="fu">na.omit</span>(data[,<span class="fu">paste0</span>(variable)])),</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>                     <span class="at">min =</span> <span class="fu">min</span>(<span class="fu">na.omit</span>(data[,<span class="fu">paste0</span>(variable)])),</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>                     <span class="at">max =</span> <span class="fu">max</span>(<span class="fu">na.omit</span>(data[,<span class="fu">paste0</span>(variable)])),</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>                     <span class="at">sd =</span> <span class="fu">sd</span>(<span class="fu">na.omit</span>(data[,<span class="fu">paste0</span>(variable)])),</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>                     <span class="do">##skew and kurtosis = loaded from "psych" package</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>                     <span class="at">skew =</span> <span class="fu">skew</span>(<span class="fu">na.omit</span>(data[,<span class="fu">paste0</span>(variable)])),</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>                     <span class="at">kurtosis =</span> <span class="fu">kurtosi</span>(<span class="fu">na.omit</span>(data[,<span class="fu">paste0</span>(variable)])))</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="do">##Add variable name</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames</span>(stat) <span class="ot">&lt;-</span> variable</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(stat)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a><span class="do">##First World descriptives</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a><span class="do">###NOTE: This code will use the function above to do the same thing as calculating</span></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a><span class="do">###mean(na.omit(filter(data, World == 1)))$Happiness</span></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a><span class="do">###median(na.omit(filter(data, World == 1)))$Happiness</span></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a><span class="do">###and so on..., but more efficiently</span></span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>World1_descriptives <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> continuous_vars){</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>  World1_descriptives <span class="ot">&lt;-</span> <span class="fu">rbind</span>(World1_descriptives, <span class="fu">stats</span>(data, <span class="dv">1</span>, i))</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a><span class="do">##Second World descriptives</span></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>World2_descriptives <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> continuous_vars){</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>  World2_descriptives <span class="ot">&lt;-</span> <span class="fu">rbind</span>(World2_descriptives, <span class="fu">stats</span>(data, <span class="dv">2</span>, i))</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a><span class="do">##Third World descriptives</span></span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a>World3_descriptives <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> continuous_vars){</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a>  World3_descriptives <span class="ot">&lt;-</span> <span class="fu">rbind</span>(World3_descriptives, <span class="fu">stats</span>(data, <span class="dv">3</span>, i))</span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a><span class="do">##Other descriptives</span></span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a>World4_descriptives <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> continuous_vars){</span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a>  World4_descriptives <span class="ot">&lt;-</span> <span class="fu">rbind</span>(World4_descriptives, <span class="fu">stats</span>(data, <span class="dv">4</span>, i))</span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a><span class="do">##Print descriptives for each of the 4 groups</span></span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a>World1_descriptives</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  mean      median     range        min        max         sd
Happiness   6.70480547  6.88408303 2.5225673  5.0808663  7.6034336 0.73846264
GDP        10.60014923 10.64544297 1.5657673  9.8642025 11.4299698 0.32164763
Support     0.91106403  0.92701676 0.2189929  0.7683506  0.9873435 0.04870113
Life       71.56475957 71.54143905 9.1287765 65.6959152 74.8246918 1.70742532
Freedom     0.83024829  0.87945190 0.4158842  0.5317363  0.9476205 0.12443371
Generosity  0.08903921  0.09993881 0.5995939 -0.2789414  0.3206525 0.17627812
Corruption  0.53832097  0.46245918 0.7551621  0.1858887  0.9410508 0.24463890
                 skew   kurtosis
Happiness  -0.6065804 -0.9398446
GDP         0.1411772  0.6439861
Support    -1.0414418  0.8896961
Life       -1.2660634  3.6405232
Freedom    -1.0713275 -0.1320270
Generosity -0.4830215 -1.0985804
Corruption  0.1443590 -1.4406387</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>World2_descriptives</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  mean     median      range        min        max        sd
Happiness   5.41721521  5.6289086  2.6434746  3.9645429  6.6080174 0.6462323
GDP         9.52518320  9.7255678  2.4384503  7.8696475 10.3080978 0.6949767
Support     0.83666469  0.8587338  0.4508536  0.5173716  0.9682252 0.1101465
Life       65.13686837 65.3385010 12.0708466 58.4413452 70.5121918 2.8034015
Freedom     0.69404760  0.6854547  0.5493451  0.4305920  0.9799371 0.1234654
Generosity -0.07555961 -0.1006917  0.6354753 -0.2624048  0.3730705 0.1350927
Corruption  0.81254055  0.8585415  0.4907340  0.4709169  0.9616510 0.1419362
                 skew    kurtosis
Happiness  -0.5471119 -0.42827226
GDP        -0.8399644 -0.40860352
Support    -1.0880440  0.61423428
Life       -0.3686089 -0.31370397
Freedom     0.2169642 -0.41724977
Generosity  1.5668417  2.77127207
Corruption -1.0444582 -0.08270774</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>World3_descriptives</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  mean       median      range         min        max        sd
Happiness   4.09701201  3.985916138  2.6520536  2.70159125  5.3536448 0.6370851
GDP         7.57284077  7.416408062  2.3556876  6.61396551  8.9696531 0.5994599
Support     0.67251744  0.678143561  0.4405574  0.43438852  0.8749459 0.1092345
Life       53.45368957 53.518108370 17.9869728 43.74033737 61.7273102 4.4635773
Freedom     0.71735941  0.733383596  0.5695738  0.39829549  0.9678693 0.1472135
Generosity  0.03863014  0.001502594  0.4555688 -0.14344171  0.3121271 0.1230534
Corruption  0.74844688  0.800046742  0.8508316  0.09460447  0.9454361 0.1750290
                  skew   kurtosis
Happiness  -0.07553877 -0.6599127
GDP         0.38636494 -0.3982235
Support    -0.22544428 -0.5128556
Life       -0.16281019 -0.4098541
Freedom    -0.37170455 -0.6048082
Generosity  0.70846934 -0.4048976
Corruption -2.08568928  4.9368252</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>World4_descriptives</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  mean      median      range         min        max        sd
Happiness   5.53322733  5.55360675  3.9860127  3.46191287  7.4479256 0.8821241
GDP         9.22070514  9.34630966  3.3854480  7.43031550 10.8157635 0.6853202
Support     0.80131986  0.82283747  0.4838877  0.46391287  0.9478006 0.1009110
Life       63.19936505 64.18115997 31.0005035 45.04415894 76.0446625 6.4534019
Freedom     0.76253840  0.79116327  0.4815910  0.44827086  0.9298619 0.1194039
Generosity -0.01301398 -0.04513925  0.7199037 -0.26247421  0.4574295 0.1520463
Corruption  0.78094526  0.81396091  0.8470234  0.09894388  0.9459673 0.1509747
                 skew    kurtosis
Happiness  -0.1774602 -0.69947279
GDP        -0.2943383  0.04544817
Support    -1.2048728  1.23805282
Life       -1.0056401  1.00840124
Freedom    -0.6542359 -0.43184493
Generosity  0.8969829  0.82680495
Corruption -2.8892466  9.69411832</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">##NOTE: The psych package also has a very handy function named describeBy() that will give you </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="do">##all the same stuff as the code above (plus some nice bonus info!):</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="do">##describeBy(data[,c(continuous_vars, "World")], group = data$World)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>##Q2 Standardize all numeric variables in the dataset, and re-run your descriptive statistics. Are there any variables that you would be concerned about? If so, which ones and why? If not, why are you not concerned?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert unstandardized variables into standardized variables </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co">#using the "scale()" function:</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>data_z <span class="ot">&lt;-</span> <span class="fu">mutate_if</span>(data, is.numeric, scale)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive statistics of standardized variables for the whole data set:</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(data_z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           vars   n  mean    sd median trimmed   mad   min    max  range  skew
Country*      1 136 68.50 39.40  68.50   68.50 50.41  1.00 136.00 135.00  0.00
Happiness     2 136  0.00  1.00  -0.01    0.01  1.08 -2.46   1.96   4.42 -0.07
GDP           3 121  0.00  1.00   0.19    0.05  1.04 -2.26   1.91   4.17 -0.43
Support       4 135  0.00  1.00   0.20    0.10  0.96 -2.99   1.51   4.50 -0.88
Life          5 135  0.00  1.00   0.20    0.08  0.98 -2.60   1.73   4.33 -0.67
Freedom       6 132  0.00  1.00   0.20    0.05  1.17 -2.64   1.71   4.34 -0.45
Generosity    7 120  0.00  1.00  -0.21   -0.06  0.94 -1.80   2.90   4.70  0.59
Corruption    8 125  0.00  1.00   0.38    0.16  0.61 -3.20   1.14   4.34 -1.48
World*        9 136  2.88  1.15   3.00    2.96  1.48  1.00   4.00   3.00 -0.45
           kurtosis   se
Country*      -1.23 3.38
Happiness     -0.69 0.09
GDP           -0.78 0.09
Support        0.11 0.09
Life          -0.34 0.09
Freedom       -0.60 0.09
Generosity    -0.27 0.09
Corruption     1.53 0.09
World*        -1.30 0.10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Descriptive statistics of standardized variables grouped by World:</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describeBy</span>(<span class="at">x =</span> data_z, <span class="at">group =</span> data_z<span class="sc">$</span>World)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Descriptive statistics by group 
group: 1
           vars  n  mean    sd median trimmed   mad   min    max  range  skew
Country       1 24 70.54 41.40  64.00   71.25 50.41  4.00 130.00 126.00 -0.07
Happiness     2 24  1.15  0.67   1.31    1.20  0.69 -0.32   1.96   2.28 -0.61
GDP           3 24  1.19  0.28   1.23    1.19  0.25  0.56   1.91   1.35  0.14
Support       4 24  0.89  0.40   1.02    0.93  0.31 -0.28   1.51   1.78 -1.04
Life          5 24  1.13  0.23   1.13    1.14  0.18  0.34   1.57   1.22 -1.27
Freedom       6 24  0.59  0.93   0.96    0.71  0.60 -1.64   1.46   3.11 -1.07
Generosity    7 23  0.55  1.13   0.62    0.61  1.30 -1.80   2.03   3.83 -0.48
Corruption    8 24 -0.98  1.23  -1.36   -1.00  1.57 -2.75   1.04   3.78  0.14
World         9 24  1.00  0.00   1.00    1.00  0.00  1.00   1.00   0.00   NaN
           kurtosis   se
Country       -1.40 8.45
Happiness     -0.94 0.14
GDP            0.64 0.06
Support        0.89 0.08
Life           3.64 0.05
Freedom       -0.13 0.19
Generosity    -1.10 0.23
Corruption    -1.44 0.25
World           NaN 0.00
------------------------------------------------------------ 
group: 2
           vars  n  mean    sd median trimmed   mad   min    max  range  skew
Country       1 27 68.04 42.14  69.00   68.43 54.86  1.00 132.00 131.00 -0.13
Happiness     2 27 -0.01  0.58   0.18    0.02  0.52 -1.32   1.06   2.38 -0.55
GDP           3 27  0.26  0.60   0.44    0.32  0.59 -1.17   0.94   2.11 -0.84
Support       4 27  0.28  0.90   0.46    0.37  0.84 -2.32   1.35   3.67 -1.09
Life          5 27  0.27  0.38   0.30    0.28  0.34 -0.63   0.99   1.62 -0.37
Freedom       6 27 -0.43  0.92  -0.49   -0.45  1.09 -2.40   1.71   4.10  0.22
Generosity    7 27 -0.50  0.86  -0.66   -0.62  0.58 -1.70   2.36   4.06  1.57
Corruption    8 26  0.39  0.71   0.62    0.47  0.50 -1.32   1.14   2.46 -1.04
World         9 27  2.00  0.00   2.00    2.00  0.00  2.00   2.00   0.00   NaN
           kurtosis   se
Country       -1.37 8.11
Happiness     -0.43 0.11
GDP           -0.41 0.12
Support        0.61 0.17
Life          -0.31 0.07
Freedom       -0.42 0.18
Generosity     2.77 0.17
Corruption    -0.08 0.14
World           NaN 0.00
------------------------------------------------------------ 
group: 3
           vars  n  mean    sd median trimmed   mad   min    max  range  skew
Country       1 27 64.26 39.41  72.00   63.39 51.89  8.00 135.00 127.00  0.10
Happiness     2 27 -1.20  0.57  -1.30   -1.19  0.58 -2.46  -0.07   2.39 -0.08
GDP           3 25 -1.43  0.52  -1.56   -1.45  0.49 -2.26  -0.22   2.04  0.39
Support       4 27 -1.06  0.89  -1.01   -1.04  0.88 -2.99   0.59   3.59 -0.23
Life          5 27 -1.30  0.60  -1.29   -1.28  0.56 -2.60  -0.19   2.41 -0.16
Freedom       6 27 -0.26  1.10  -0.14   -0.22  1.07 -2.64   1.62   4.25 -0.37
Generosity    7 25  0.23  0.79  -0.01    0.18  0.58 -0.94   1.97   2.91  0.71
Corruption    8 27  0.07  0.88   0.33    0.21  0.50 -3.20   1.06   4.26 -2.09
World         9 27  3.00  0.00   3.00    3.00  0.00  3.00   3.00   0.00   NaN
           kurtosis   se
Country       -1.39 7.58
Happiness     -0.66 0.11
GDP           -0.40 0.10
Support       -0.51 0.17
Life          -0.41 0.12
Freedom       -0.60 0.21
Generosity    -0.40 0.16
Corruption     4.94 0.17
World           NaN 0.00
------------------------------------------------------------ 
group: 4
           vars  n  mean    sd median trimmed   mad   min    max  range  skew
Country       1 58 69.84 38.14  67.00   69.50 45.96  2.00 136.00 134.00  0.06
Happiness     2 58  0.09  0.80   0.11    0.12  0.96 -1.78   1.82   3.60 -0.18
GDP           3 45  0.00  0.59   0.11    0.02  0.49 -1.55   1.38   2.93 -0.29
Support       4 57 -0.01  0.82   0.17    0.09  0.67 -2.75   1.19   3.94 -1.20
Life          5 57  0.01  0.86   0.14    0.10  0.62 -2.42   1.73   4.15 -1.01
Freedom       6 54  0.08  0.89   0.30    0.15  1.00 -2.27   1.33   3.60 -0.65
Generosity    7 45 -0.10  0.97  -0.31   -0.18  0.77 -1.70   2.90   4.60  0.90
Corruption    8 48  0.24  0.76   0.40    0.35  0.39 -3.18   1.06   4.24 -2.89
World         9 58  4.00  0.00   4.00    4.00  0.00  4.00   4.00   0.00   NaN
           kurtosis   se
Country       -1.20 5.01
Happiness     -0.70 0.10
GDP            0.05 0.09
Support        1.24 0.11
Life           1.01 0.11
Freedom       -0.43 0.12
Generosity     0.83 0.14
Corruption     9.69 0.11
World           NaN 0.00</code></pre>
</div>
</div>
<p>This is an open question, so a number of responses are valid.</p>
<p>##Q3 Calculate the population variance and standard deviations by hand (aka don’t use a particular variance or standard deviation function) for any 3 numeric variables.</p>
<p>Note the na.omit() function can be handy with missing data. This will get rid of any NA values, and make your calculations easier.</p>
<p>Calculate the population variance using the formula sum((X - M)^2)/N. Then, take the square root of the variance to get the population standard deviation. Because this is a population variance, N is used as the denominator rather than N - 1 (as in the sample variance).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Define a function to calculate the population variance and standard deviation by hand</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>dispersion <span class="ot">&lt;-</span> <span class="cf">function</span>(variable){</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data[,variable])</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  variance <span class="ot">&lt;-</span> <span class="fu">sum</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">length</span>(x)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  sd <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(variance)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(variance, sd)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames</span>(result) <span class="ot">&lt;-</span> variable</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(result)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="do">##Run the function on 3 variables, save each result to a dataframe</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>variances <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"Happiness"</span>, <span class="st">"GDP"</span>, <span class="st">"Support"</span>)){</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  variances <span class="ot">&lt;-</span> <span class="fu">rbind</span>(variances, <span class="fu">dispersion</span>(i))</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>variances</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           variance        sd
Happiness 1.2199099 1.1044953
GDP       1.3246706 1.1509433
Support   0.0149711 0.1223564</code></pre>
</div>
</div>
<p>##Q4 Create a violin plot (a new and improved box plot) for the Corruption variable, with plots for the four groups defined by the new variable, World. What does this graph tell you, in broad strokes, about:</p>
<ol type="1">
<li>group differences in corruption central tendency?</li>
<li>group differences in corruption variability?</li>
<li>the presence of outliers within each group?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Violin Plot Code:</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data, <span class="fu">aes</span>(<span class="at">x =</span> World, <span class="at">y =</span> Corruption, <span class="at">fill =</span> World))<span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>()<span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 11 rows containing non-finite outside the scale range
(`stat_ydensity()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HW_1_KEY_files/figure-html/Q4 Code-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="1">
<li><p>As reflected in the medians, relative to the differences between other country groups, the central tendency for “first-world” countries is substantially lower than the other groups.</p></li>
<li><p>Relative to the differences between other country groups, there is substantially more variation in the Corruption distribution for “first-world” countries than the other groups.</p></li>
<li><p>Second, Third, and fourth world counties appear to have outliers which are scewing the data. The outliers in third and fourth world countries appear to be more extreme.</p></li>
</ol>
<p>##Q5 ##Part A Calculate the correlation for Happiness &amp; Freedom, Happiness &amp; Support, and finally Freedom &amp; Support.</p>
<p>###Part B Now make a scatterplot for each of these 3 relationships. Include a linear best fit “regresion” line (a straight line). - How does the best fit lines correspond to the correlations that you got in Part A of this question? - Does a linear relationship seem to describe any of the pairwise relationships?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Calculate 3 correlations</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(data<span class="sc">$</span>Happiness, data<span class="sc">$</span>Freedom, <span class="at">use =</span> <span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5145117</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(data<span class="sc">$</span>Happiness, data<span class="sc">$</span>Support, <span class="at">use =</span> <span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7258971</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(data<span class="sc">$</span>Freedom, data<span class="sc">$</span>Support, <span class="at">use =</span> <span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3484636</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Plot the three relationships</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="do">###Happiness ~ Freedom</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Happiness, <span class="at">y =</span> Freedom), <span class="at">data =</span> data)<span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HW_1_KEY_files/figure-html/q5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">###Happiness ~ Support</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Happiness, <span class="at">y =</span> Support), <span class="at">data =</span> data)<span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HW_1_KEY_files/figure-html/q5-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">###Freedom ~ Support</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Freedom, <span class="at">y =</span> Support), <span class="at">data =</span> data)<span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HW_1_KEY_files/figure-html/q5-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>The positive slope of the three regression lines corresponds to the positive correlations between eacah pair of variables. The spread of datapoints around the regression line is (a) tightest for Happiness and Support showing a strong correlation, (b) slightly less tight for Happiness and Freedom showing a slightly weaker correlation, (c) least tight for Freedom and Support showing the weakest correlation.</p></li>
<li><p>Each of the three pairwise relationships seems to be captured by a positive linear relationship. For the relationship between Freedom and Support, a large portion of the data are in the upper right quadrant of the scatterplot and relatively less data is in the lower quadrants, making the linear relationship somewhat less clear.</p></li>
</ul>
<p>##Q6</p>
<p>####Part A Calculate the regression coefficient by hand for Happiness &amp; Freedom with Happiness as the DV, and Freedom as the IV.</p>
<p>Interpret the regression coefficient</p>
<p>Without doing any new calculations, assume that the regression coefficient you just calculated was the output of a standardized regression i.e., both your Y and X were standardized. Interpret this regression coefficient.</p>
<p>The formula for the beta1 regression coefficient is (rxy * Sy) / Sx:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculation of the Regression Coefficient:</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlation of Freedom and Happiness:</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>rFreeHapp <span class="ot">&lt;-</span> <span class="fu">cor</span>(data<span class="sc">$</span>Freedom, data<span class="sc">$</span>Happiness, <span class="at">use =</span> <span class="st">"pairwise"</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Standard Deviation of Freedom:</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>sdFree <span class="ot">&lt;-</span> <span class="fu">sd</span>(<span class="fu">na.omit</span>(data<span class="sc">$</span>Freedom))</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Standard Deviation of Happiness:</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>sdHapp <span class="ot">&lt;-</span> <span class="fu">sd</span>(<span class="fu">na.omit</span>(data<span class="sc">$</span>Happiness))</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> (rFreeHapp <span class="sc">*</span> sdHapp) <span class="sc">/</span> sdFree</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>beta1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.260772</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculation of the Regression Coefficient if the variables were standardized:</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlation of Freedom and Happiness:</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>rFreeHapp_z <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">cor</span>(data_z<span class="sc">$</span>Freedom, data_z<span class="sc">$</span>Happiness, <span class="at">use =</span> <span class="st">"pairwise"</span>))</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Standard Deviation of Freedom:</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>sdFree_z <span class="ot">&lt;-</span> <span class="fu">sd</span>(<span class="fu">na.omit</span>(data_z<span class="sc">$</span>Freedom))</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Standard Deviation of Happiness:</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>sdHapp_z <span class="ot">&lt;-</span> <span class="fu">sd</span>(<span class="fu">na.omit</span>(data_z<span class="sc">$</span>Happiness))</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>beta1_z <span class="ot">&lt;-</span> (rFreeHapp_z <span class="sc">*</span> sdHapp_z) <span class="sc">/</span> sdFree_z</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>beta1_z</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5145117</code></pre>
</div>
</div>
<p>Interpreting the regression coefficient in raw units: For a one unit increase in Freedom, Happiness is expected to increase by 4.43.</p>
<p>Interpreting the regression coefficient in raw units as if it were standardized: For a one standard deviation increase in Freedom, Happiness is expected to increase by 4.43 standard deviations.</p>
<p>regression coefficient in standardized units: For a one standard deviation increase in Freedom, Happiness is expected to increase by 0.51 standard deviations.</p>
<p>####Part B Calculate the standard error of the regression coefficient ‘by hand’ using sigma.</p>
<p>The formula for the standard error of the regression coefficient (beta1) is RSE / sqrt(SSD), where RSE is the residual Standard Error (Sigma) and SSD is the Sum of Squared Deviations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model for the Happiness predicted by Freedom:</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>FreeHappmodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> Freedom, <span class="at">data =</span> data)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co">#RSE</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>RSE <span class="ot">&lt;-</span> <span class="fu">sigma</span>(FreeHappmodel)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Get the deviations from the mean for Freedom:</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Freedom_differences <span class="ot">&lt;-</span> data<span class="sc">$</span>Freedom <span class="sc">-</span> <span class="fu">mean</span>(<span class="fu">na.omit</span>(data<span class="sc">$</span>Freedom))</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Square the deviations:</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Freedom_differences_sq <span class="ot">&lt;-</span> data<span class="sc">$</span>Freedom_differences<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Sum of Squared deviations:</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>ssd_Freedom <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">na.omit</span>(data<span class="sc">$</span>Freedom_differences_sq))</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="co">#square root the Sum of Squared Deviations:</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>denominator <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(ssd_Freedom)</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate the Standard Error:</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>SEbeta1 <span class="ot">&lt;-</span> RSE <span class="sc">/</span> denominator</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>SEbeta1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6293763</code></pre>
</div>
</div>
<p>##Q7</p>
<p>Using functions presented in class, create a data frame that includes the predicted/fitted values and the residuals. Calculate the mean and SD of each of these values. - What statistic is the mean of fitted values equal to? - What statistic does the the SD of the residuals conceptually equal?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Run lm version of the model</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> Freedom, <span class="at">data =</span> data)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="do">##Using augment() from the broom package, get the fitted values and residuals</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">augment</span>(mod)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="do">###Mean Yhat</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(predictions<span class="sc">$</span>.fitted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.4335</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">na.omit</span>(data[,<span class="fu">c</span>(<span class="st">"Happiness"</span>, <span class="st">"Freedom"</span>)])<span class="sc">$</span>Happiness)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.4335</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(predictions<span class="sc">$</span>.fitted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5764013</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="do">###SD of residuals</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(predictions<span class="sc">$</span>.resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.435762e-15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(predictions<span class="sc">$</span>.resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9606285</code></pre>
</div>
</div>
<ul>
<li>The mean of fitted values is equal to the mean of the DV/Y (Happiness).</li>
<li>The SD of the residuals is conceptually equal to Sigma. (Note: the actual number is different, because the denominator for the sd() function is n - 1, whereas the denominator for Sigma is n - k - 1)</li>
</ul>
<p>##Q8</p>
<p>Graph the PDF and CDF of Y ~ t(3, 3, .5)</p>
<p>For Q8, we are looking for a distribution where Y ~ t(3,3,.5). The first number refers to the degrees of freedom. The second number refers to the population mean, mu. The third number refers to the population standard deviation, sigma.</p>
<p>Using the dt() function, you can only specify degrees of freedom. mu and sigma are standardized, meaning that they are set to 0 and 1, respectively. To unstandardize them to the values above, we can use this equation: x = Z * sigma + mu, which is the inverse of the standardization equation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Distribution parameters:</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> .<span class="dv">5</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="do">##Create a sequence of numbers which will function as standardized t-values</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="co">#for the purpose of obtaining Pdata and Cdata values:</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>Zt <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">200</span>)</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Get Pdata and Cdatavalues for those t-values given the degrees of freedom:</span></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>Pdata <span class="ot">&lt;-</span> <span class="fu">dt</span>(Zt,df)</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>Cdata <span class="ot">&lt;-</span> <span class="fu">pt</span>(Zt,df)</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Unstandardize the t-values according to the given parameters:</span></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> Zt <span class="sc">*</span> sigma <span class="sc">+</span> mu</span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Put them together in a dataframe:</span></span>
<span id="cb59-18"><a href="#cb59-18" aria-hidden="true" tabindex="-1"></a>t_dist_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Zt, Pdata, Cdata, t)</span>
<span id="cb59-19"><a href="#cb59-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-20"><a href="#cb59-20" aria-hidden="true" tabindex="-1"></a><span class="do">##Plot the Pdata distribution:</span></span>
<span id="cb59-21"><a href="#cb59-21" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(t_dist_data) <span class="sc">+</span></span>
<span id="cb59-22"><a href="#cb59-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> Pdata))<span class="sc">+</span></span>
<span id="cb59-23"><a href="#cb59-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"t(3,3,.5)"</span>)<span class="sc">+</span></span>
<span id="cb59-24"><a href="#cb59-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW_1_KEY_files/figure-html/Q8 Code-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Plot the Cdata distribution:</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(t_dist_data) <span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> t, <span class="at">y =</span> Cdata))<span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"t(3,3,.5)"</span>)<span class="sc">+</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW_1_KEY_files/figure-html/Q8 Code-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>##Q9 Psychological and educational tests, including the MMPI (Minnesota Multiphasic Personality Inventory), are often designed so they have a mean of 50 and a standard deviation of 10, and assumed to be normally distributed.</p>
<ul>
<li>The MMPI says that scores that are two standard deviations or more above the mean may indicate pathology. Among a thousand people, how many would be expected to have scores two standard deviations or more above the mean?</li>
<li>What proportion would be expected to score 68 or above?</li>
<li>What proportion would be expected to score between 53 and 63?</li>
<li>What value corresponds to the 89th percentile of scores? 5th percentile?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Proof for proportion &gt; 2 SDs above the mean</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">50</span><span class="sc">+</span>(<span class="dv">2</span><span class="sc">*</span><span class="dv">10</span>), <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02275013</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Proportion above 68</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">68</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03593032</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Proportion between 53 - 63</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">63</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">53</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2852881</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="do">##89th and 5th percentiles</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> .<span class="dv">89</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 62.26528</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> .<span class="dv">05</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33.55146</code></pre>
</div>
</div>
<ul>
<li>~2.28% would have scores 2 SDs above the mean or greater.</li>
<li>~3.6% would have scores of 68 or greater.</li>
<li>~28.5% would have scores between 53 and 63.</li>
<li>A score of ~62.26 corresponds to the 89th percentile, and a score of ~33.55 corresponds to the 5th percentile.</li>
</ul>
<p>##Q10 Filter your World variable to set up a regression where you are comparing whether world coded 1 differs from world coded 3 on Freedom.</p>
<ol type="1">
<li>Interpret the intercept</li>
<li>Interpret the regression coefficient</li>
<li>What is the predicted value for group coded 1, group coded 3?</li>
<li>What would you change if you wanted your intercept to have a different interpretation?</li>
<li>What effect size metric would you use to describe your results?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Filter the dataframe such that only World = 1 and World = 3 are included:</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>homework.world1 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"homework-world.csv"</span>)</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>data_filtered <span class="ot">&lt;-</span> homework.world1 <span class="sc">|&gt;</span> </span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(World <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">World =</span> <span class="fu">as.factor</span>(World))</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a regression model for Freedom predicted by World</span></span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a><span class="co">#(</span><span class="al">NOTE</span><span class="co">: At the beginning of my code, I set the World variable as a factor variable</span></span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a><span class="co">#rather than an int or num variable. By default, this means that First World Countries</span></span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Will be interpreted as X = 0 and Third World Countries will be interpreted as X = 1.</span></span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a><span class="co">#If you don't do this, your results will look very different and should be interpreted differently). Treating World as a categorical (factor) variable is the correct way to</span></span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a><span class="co">#run this model:</span></span>
<span id="cb71-17"><a href="#cb71-17" aria-hidden="true" tabindex="-1"></a>model1v3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Freedom <span class="sc">~</span> World, <span class="at">data =</span> data_filtered)</span>
<span id="cb71-18"><a href="#cb71-18" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1v3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Freedom ~ World, data = data_filtered)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.31906 -0.08054  0.03923  0.09750  0.25051 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.83025    0.02796  29.690  &lt; 2e-16 ***
World3      -0.11289    0.03843  -2.937  0.00503 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.137 on 49 degrees of freedom
Multiple R-squared:  0.1497,    Adjusted R-squared:  0.1324 
F-statistic: 8.628 on 1 and 49 DF,  p-value: 0.005033</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Getting the effect size (Not required):</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model1v3, <span class="st">"World"</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">eff_size</span>(emm, <span class="at">sigma =</span> <span class="fu">sigma</span>(model1v3), <span class="at">edf =</span> <span class="fu">df.residual</span>(model1v3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast        effect.size    SE df lower.CL upper.CL
 World1 - World3       0.824 0.293 49    0.236     1.41

sigma used for effect sizes: 0.137 
Confidence level used: 0.95 </code></pre>
</div>
</div>
<ol type="1">
<li><p>The predicted freedom value for First World Countries is 0.83.</p></li>
<li><p>The Third World Countries are expected to have freedom values 0.11 units less than First World Countries.</p></li>
<li><p>The predicted freedom value for First World Countries is 0.83. The predicted freedom value for Third World Countries is .696 (0.83025 - 0.11289).</p></li>
<li><p>You could, for example, use contr.sum(2) function so that the intercept is between First World Countries and Third World Countries. Or you can manually code 0 and 1s.</p></li>
<li><p>Cohen’s D would be appropriate. .11 (difference) / .137 (pooled sd) = .824.</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>